### ISSUE TITLE
Any walk-through on how to use?

### ISSUE THREAD

**Issue by domagal9** [mat701/BiCM#1]
Hello! 

I've been playing with this package in python and I think it's doing what I want but am not positive. Are there any walk-throughs/manuals on how to use all of the package functions?

Thanks!
Rachel

**Comment by mat701** [comment]
Hi Rachel,

I am writing a better documentation and some better test files right now, for the moment you can find a first read the docs at https://bicm-beta.readthedocs.io/en/latest/ .

If you need any help you can contact me at matteo.bruno@imtlucca.it . The package has just been published so every comment is appreciated!

Matteo

**Comment by domagal9** [comment]
Oh wonderful this will help a lot! Thank you!!
