### ISSUE TITLE
numba dependency not installed

### ISSUE THREAD

**Issue by jboynyc** [mat701/BiCM#3]
The `numba` dependency is [not specified in `setup.py`](https://github.com/mat701/BiCM/blob/master/setup.py#L26). 

Without `numba` installed, you cannot even import `BipartiteGraph`, so it seems it should be required and installed along with the `bicm` package.

**Comment by mat701** [comment]
We had decided to leave this open for the user as numba was a bit hard to install some years ago. Perhaps it is now time to change it as the numba installation seems to be more straightforward

**Comment by jboynyc** [comment]
Makes sense! I suppose an alternative would be to wrap the import of numba in a try/except block and either fall back to a slower version or warn users that numba should be installed separately. But I see this point is now moot, since you added the dependency to setup.py.
